### ISSUE TITLE
Замечания по lw2/task1

### ISSUE THREAD

**Issue by ivklgn** [Umk1n/web-development-course#2]
именование картинок с маленькой буквы

**Comment by ivklgn** [comment]
```html
            <button class="button-content">SMALL BUTTON</button>
```

используйте css свойство http://htmlbook.ru/css/text-transform, uppercase

**Comment by ivklgn** [comment]
в css нарушено форматирование

**Comment by ivklgn** [comment]
```css
p{
  display: flex;
  line-height: 24px;
  color: #414141;
  width: 388px;
  margin: 12px 0px 0px 0px;
}
```

- стилизуйте по классу
- параграф не должен быть flex-контейнером, так как не содержит дочерние элементы 

------------


```html
          <div class="text">Sagittis, eu pretium massa quisque cursus augue massa cursus. Sed quisque velit,
            auctor at lobortis hac tincidunt sodales id. Elit interdum vel nisi, in enim sagittis at.
            Netus sagittis eleifend aliquet urna quis.
          </div>
```

.text - так или иначе не flex

**Comment by ivklgn** [comment]
```html
    <h1>Our <span class="underline">Programs</span></h1>
```

лучше стилизовать не по селектору `.header h1 .underline`, а присвоить h1 класс `.header-title`


-----------

`.header h1 .underline` -> `.header-title .underline`

**Comment by ivklgn** [comment]
у вас не должно быть 2 класса на разные строки .row и row-1, сделайте один flex контейнер который содержит все элементы построчно и реализуйте сброс элементов по 2 в строке

**Comment by ivklgn** [comment]
избавьтесь от этих классов:

```css
.dark-h{
  color: #FFFFFF;
}
.dark-p{
  color: rgba(255, 255, 255, 0.8);
}
```

используйте один класс black и каскадирование дочерних с помощью одного класса

**Comment by ivklgn** [comment]
`button-content -> button`

button не flex-контейнер (!)

**Comment by ivklgn** [comment]
```css
.text-content h2 {
  width: 388px;
  height: 40px;
  font-size: 35px;
  line-height: 40px;
  display: flex;
  align-items: center;
  margin: 4px 0px;
}
```
это так же стилизация по тегу
